In [2]:
import numpy as np

1.生成 NumPy 数组

In [3]:
x = np.array([1.0, 2.0, 3.0])
x,type(x)

(array([1., 2., 3.]), numpy.ndarray)

In [5]:
#np.arange(start=0, stop, step=1, dtype=None)
import numpy as np
print(np.arange(3))  # 输出：array([0, 1, 2])
print(np.arange(1, 5) ) # 输出：array([1, 2, 3, 4])

print(np.arange(0, 10, 2) ) # 步长2，输出：array([0, 2, 4, 6, 8])
print(np.arange(5, 0, -1) ) # 逆序生成，输出：array([5, 4, 3, 2, 1])
print(np.arange(0, 1, 0.1) ) # 浮点步长，输出：array([0. , 0.1, 0.2, ..., 0.9])

[0 1 2]
[1 2 3 4]
[0 2 4 6 8]
[5 4 3 2 1]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


2.NumPy 的算术运算

In [ ]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y,x - y,x * y,x / y,x / 2.0 #广播，与标量相乘

(array([3., 6., 9.]),
 array([-1., -2., -3.]),
 array([ 2.,  8., 18.]),
 array([0.5, 0.5, 0.5]),
 array([0.5, 1. , 1.5]))

3.NumPy 的 N 维数组

In [14]:
A = np.array([[1, 2], [3, 4]]) #二维数组，矩阵
A,A.shape,A.dtype

(array([[1, 2],
        [3, 4]]),
 (2, 2),
 dtype('int64'))

In [18]:
B = np.array([[3, 0],[0, 6]])
B,A + B,A * B,A*10

(array([[3, 0],
        [0, 6]]),
 array([[ 4,  2],
        [ 3, 10]]),
 array([[ 3,  0],
        [ 0, 24]]),
 array([[10, 20],
        [30, 40]]))

4.广播

In [22]:
#前例中，标量 10 被当作 2 × 2 的矩阵，([[10, 10],[10, 10]])
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])#=([[10, 20],[10, 20]])
A * B

array([[10, 40],
       [30, 80]])

5.访问元素

In [ ]:
X = np.array([[51, 55], [14, 19], [0, 4]])
X

array([[51, 55],
       [14, 19],
       [ 0,  4]])

In [30]:
X[0] # 第 0 行

array([51, 55])

In [ ]:
X[0][1],X[0,1]  # (0,1) 的元素 ,两种表示


(55, 55)

In [36]:
X = X.flatten()# 将 X 转换为一维数组
X

array([51, 55, 14, 19,  0,  4])

In [37]:
X[np.array([0, 2, 4])] # 获取索引为 0、2、4 的元素

array([51, 14,  0])

In [ ]:
X > 15,X[X>15]
#对 NumPy 数组使用不等号运算会得到布尔型的数组，再加上X会取出数组元素

(array([ True,  True, False,  True, False, False]), array([51, 55, 19]))

6.多维数组

In [ ]:
#一维数组
import numpy as np
A = np.array([1, 2, 3, 4])
print(A)
# np.ndim() :数组维数（行数）
#A.shape  : 数组的形状（几行几列）
#A.shape[0]：行数，1是列数
np.ndim(A),A.shape,A.shape[0] 

[1 2 3 4]


(1, (4,), 4)

In [ ]:
#二维数组/矩阵
B = np.array([[1,2], [3,4], [5,6]])
print(B)
np.ndim(B),B.shape

[[1 2]
 [3 4]
 [5 6]]


(2, (3, 2))

In [ ]:
#矩阵运算1
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
A.shape,B.shape,np.dot(A, B),np.dot(B, A)

((2, 2),
 (2, 2),
 array([[19, 22],
        [43, 50]]),
 array([[23, 34],
        [31, 46]]))

In [ ]:
##矩阵运算2:A列数 = B行数 → A行B列
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[1,2], [3,4], [5,6]])
A.shape,B.shape,np.dot(A, B),np.dot(B, A)

((2, 3),
 (3, 2),
 array([[22, 28],
        [49, 64]]),
 array([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]]))

In [ ]:
#矩阵运算3 :A是二维数组，B是一维数组，元素个数仍保持一致
A = np.array([[1,2], [3, 4], [5,6]]) #(3x2)
B = np.array([7,8]) #(2x1)
A.shape,B.shape,np.dot(A, B) #结果得2相当于行数对应A的列数 因为一维数组相当于列向量，内积的形状为 (3,)，还是列向量

((3, 2), (2,), array([23, 53, 83]))